[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-10_x", "openssl"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --config.optional=true"]

[phases.build]
cmds = ["NODE_OPTIONS=--max-old-space-size=1024 pnpm run build"]

[start]
cmd = "pnpm run start"
