[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-10_x", "openssl"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile --config.optional=true"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
